from typing import Optional
from fastapi import APIRouter, Query

from app.features.news.schema import CurrentsNewsResponse, NormalizedNewsResponse, NewsDetailResponse
from app.features.news.currents_service import currents_service
from app.features.news.providers.factory import NewsProviderFactory

router = APIRouter(prefix="/news", tags=["News"])

@router.get("/latest", response_model=CurrentsNewsResponse)
async def get_latest_news(
    language: Optional[str] = Query(None, description="Language code (e.g. en)"),
    country: Optional[str] = Query(None, description="ISO country code (e.g. US, IN)"),
    category: Optional[str] = Query(None, description="Category name"),
    page_size: int = Query(20, ge=1, le=20, description="Number of results per page"),
    cursor: Optional[str] = Query(None, description="Cursor for pagination")
):
    """
    Get the latest news articles.
    """
    return await currents_service.get_latest_news(
        language=language,
        country=country,
        category=category,
        page_size=page_size,
        cursor=cursor
    )


@router.get("/search", response_model=CurrentsNewsResponse)
async def search_news(
    keywords: Optional[str] = Query(None, description="Search keywords"),
    category: Optional[str] = Query(None, description="Category name"),
    country: Optional[str] = Query(None, description="ISO country code"),
    language: Optional[str] = Query(None, description="Language code"),
    author: Optional[str] = Query(None, description="Author name"),
    domain: Optional[str] = Query(None, description="Domain name (e.g. bbc.com)"),
    start_date: Optional[str] = Query(None, description="Start date (YYYY-MM-DD)"),
    end_date: Optional[str] = Query(None, description="End date (YYYY-MM-DD)"),
    page_size: int = Query(20, ge=1, le=20),
    cursor: Optional[str] = Query(None, description="Cursor for pagination")
):
    """
    Search for news articles with advanced filters.
    """
    return await currents_service.search_news(
        keywords=keywords,
        category=category,
        country=country,
        language=language,
        author=author,
        domain=domain,
        start_date=start_date,
        end_date=end_date,
        page_size=page_size,
        cursor=cursor
    )


@router.get("/trending", response_model=CurrentsNewsResponse)
async def get_trending_news():
    """
    Get the latest trending news (top 20 articles).
    """
    return await currents_service.get_trending_news()


@router.get("/breaking", response_model=CurrentsNewsResponse)
async def get_breaking_news():
    """
    Get the top 10 breaking news articles.
    """
    return await currents_service.get_breaking_news()


@router.get("/category/{category}", response_model=CurrentsNewsResponse)
async def get_news_by_category(
    category: str,
    page_size: int = Query(20, ge=1, le=20),
    cursor: Optional[str] = Query(None)
):
    """
    Get latest news for a specific category.
    Supported categories: general, politics_government, economy_business_finance, etc.
    """
    return await currents_service.get_latest_news(
        category=category,
        page_size=page_size,
        cursor=cursor
    )


@router.get("/country/{country_code}", response_model=CurrentsNewsResponse)
async def get_news_by_country(
    country_code: str,
    page_size: int = Query(20, ge=1, le=20),
    cursor: Optional[str] = Query(None)
):
    """
    Get latest news for a specific country using its ISO code (e.g., IN, US).
    """
    return await currents_service.get_latest_news(
        country=country_code,
        page_size=page_size,
        cursor=cursor
    )


@router.get("/keyword/{keyword}", response_model=CurrentsNewsResponse)
async def search_news_by_keyword(
    keyword: str,
    page_size: int = Query(20, ge=1, le=20),
    cursor: Optional[str] = Query(None)
):
    """
    Search news specifically by a keyword (e.g. Artificial Intelligence, Tesla).
    """
    return await currents_service.search_news(
        keywords=keyword,
        page_size=page_size,
        cursor=cursor
    )


@router.get("/article/{article_id}", response_model=NewsDetailResponse)
async def get_article_detail(article_id: str):
    """
    Get detailed information about a specific article, including mocked full content and video.
    """
    # Simulate a DB lookup or API fetch
    mock_content = (
        "This is a simulated full article body generated by the backend because the upstream news provider "
        "only provided a brief description.\\n\\nIn a real-world scenario with a premium API key, this "
        "would contain the full text of the article. We are using an embedded video to enrich the experience."
    )
    mock_video = "https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&showinfo=0&controls=1"

    return NewsDetailResponse(
        id=article_id,
        title="Article Detail Example",
        description="This is the description.",
        image="https://via.placeholder.com/600x400",
        category="general",
        source="System",
        published_at=None,
        content="Short content...",
        full_content=mock_content,
        video_url=mock_video,
        source_url="https://example.com"
    )

# ==========================================
# India News Endpoints (Powered by NewsData.io)
# ==========================================

@router.get("/india/latest", response_model=NormalizedNewsResponse)
async def get_india_latest_news(
    category: Optional[str] = Query(None, description="Category name"),
    cursor: Optional[str] = Query(None, description="Cursor for pagination (page token)")
):
    """
    Get the latest news articles from India.
    """
    provider = NewsProviderFactory.get_newsdata_provider()
    return await provider.get_latest_news(
        country="in",
        category=category,
        cursor=cursor
    )


@router.get("/india/search", response_model=NormalizedNewsResponse)
async def search_india_news(
    keywords: Optional[str] = Query(None, description="Search keywords"),
    category: Optional[str] = Query(None, description="Category name"),
    language: Optional[str] = Query(None, description="Language code"),
    cursor: Optional[str] = Query(None, description="Cursor for pagination")
):
    """
    Search for news articles from India.
    """
    provider = NewsProviderFactory.get_newsdata_provider()
    return await provider.search_news(
        keywords=keywords,
        category=category,
        country="in",
        language=language,
        cursor=cursor
    )


@router.get("/india/category/{category}", response_model=NormalizedNewsResponse)
async def get_india_news_by_category(
    category: str,
    cursor: Optional[str] = Query(None)
):
    """
    Get latest India news for a specific category.
    """
    provider = NewsProviderFactory.get_newsdata_provider()
    return await provider.get_latest_news(
        country="in",
        category=category,
        cursor=cursor
    )
