"""refactor_bookmarks

Revision ID: e4b1f62c62e3
Revises: 4821948c863e
Create Date: 2026-07-16 08:42:00.719531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b1f62c62e3'
down_revision: Union[str, Sequence[str], None] = '4821948c863e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('article_id', sa.String(), nullable=False))
    op.add_column('bookmarks', sa.Column('title', sa.String(), nullable=False))
    op.add_column('bookmarks', sa.Column('url', sa.String(), nullable=False))
    op.add_column('bookmarks', sa.Column('image', sa.String(), nullable=True))
    op.add_column('bookmarks', sa.Column('source_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_bookmarks_news_id'), table_name='bookmarks')
    op.drop_constraint(op.f('uq_bookmark_user_news'), 'bookmarks', type_='unique')
    op.create_index(op.f('ix_bookmarks_article_id'), 'bookmarks', ['article_id'], unique=False)
    op.create_unique_constraint('uq_bookmark_user_article', 'bookmarks', ['user_id', 'article_id'])
    op.drop_constraint(op.f('fk_bookmarks_news_id_news'), 'bookmarks', type_='foreignkey')
    op.drop_column('bookmarks', 'news_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('news_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_bookmarks_news_id_news'), 'bookmarks', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_bookmark_user_article', 'bookmarks', type_='unique')
    op.drop_index(op.f('ix_bookmarks_article_id'), table_name='bookmarks')
    op.create_unique_constraint(op.f('uq_bookmark_user_news'), 'bookmarks', ['user_id', 'news_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_bookmarks_news_id'), 'bookmarks', ['news_id'], unique=False)
    op.drop_column('bookmarks', 'source_name')
    op.drop_column('bookmarks', 'image')
    op.drop_column('bookmarks', 'url')
    op.drop_column('bookmarks', 'title')
    op.drop_column('bookmarks', 'article_id')
    # ### end Alembic commands ###
